#服务器
server:
  port: 8080
  tomcat:
    #*.jar
    additional-tld-skip-patterns: .jar
    max-threads: 100


    uri-encoding: UTF-8

spring:
  banner:
    charset: UTF-8
  freemarker:
    cache: false
    charset: UTF-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/template/
    suffix: .flt
  resources:
    static-locations: [classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/]

    chain:
      strategy:
        content:
          enabled: true
          # Comma-separated list of patterns to apply to the Version Strategy.
          paths: /**
          # Enable the fixed Version Strategy.当我们资源内容发生变化时，由于浏览器缓存，用户本地的静态资源还是旧的资源，为了防止这种情况导致的问题，我们可能会手动在请求url的时候加个版本号或者其他方式。
          #此时在springboot中，我们可以通过如下两种方式解决此问题。
        fixed:
          enabled: true
          # Comma-separated list of patterns to apply to the Version Strategy.
          paths: /**
          # Version string to use for the Version Strategy.
          version: v1.0.0
      # Locations of static resources.
  thymeleaf:
    # Enable template caching. 开发阶段关闭缓存  不然没法看到实时页面
    cache: false
    # Check that the template exists before rendering it.
    check-template: true
    servlet:
      # Content-Type value.
      content-type: text/html
      # Template encoding.
    encoding: utf-8
    #spring.thymeleaf.excluded-view-names= # Comma-separated list of view names that should be excluded from resolution.
    mode: HTML
    # Prefix that gets prepended to view names when building a URL.
    prefix: classpath:/template/
    # Suffix that gets appended to view names when building a URL.
    suffix: .html
  jackson:
    serialization:
      indent_output: true
  jpa:
    open-in-view: true
  redis:
    host: 192.168.3.108
    port: 6379
  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 2500MB

hdfs:
  #hdfs namenode地址
  url: hdfs://192.168.106.100:9000/
  #hdfs 用户
  user: root
