spring:
  banner:
    charset: UTF-8
  freemarker:
    cache: false
    charset: UTF-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/template/
    suffix: .flt
  resources:
    static-locations: [classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/]
    chain:
      strategy:
        content:
          enabled: true
          # Comma-separated list of patterns to apply to the Version Strategy.
          paths: /**
          # Enable the fixed Version Strategy.当我们资源内容发生变化时，由于浏览器缓存，用户本地的静态资源还是旧的资源，为了防止这种情况导致的问题，我们可能会手动在请求url的时候加个版本号或者其他方式。
          #此时在springboot中，我们可以通过如下两种方式解决此问题。
        fixed:
          enabled: true
          # Comma-separated list of patterns to apply to the Version Strategy.
          paths: /**
          # Version string to use for the Version Strategy.
          version: v1.0.0
      # Locations of static resources.
  jackson:
    serialization:
      indent_output: true
  jpa:
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 192.168.106.19
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host:
    listener:
      study:
        queue:
          name: annotation-queue
          declare: true
        exchange:
          name: annotation-exchange
          declare: true
          type: topic
          ignoreDeclarationException: true
        key: annotation-key
      simple:
        #手动签收
        acknowledge-mode: manual
        #默认接收大小
        concurrency: 5
        max-concurrency: 10

hdfs:
  #hdfs namenode地址
  url: hdfs://192.168.106.100:9000/
  #hdfs 用户
  user: root
